name: techcamp-2023
services:
  pos_web:
    image: node:18-slim
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        yarn install
        yarn start
    environment:
      - PORT=8001
      - API_HOST=host.docker.internal:8011
    ports:
      - 8001:8001
    volumes:
      - ./pos:/app
      - pos-node-modules:/app/node_modules
      - pos-parcel-cache:/app/.parcel-cache
  pos_api:
    image: rubylang/ruby:3.2-dev-jammy
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        bundle install
        ./bin/rails s -p 8011 -b 0.0.0.0
    ports:
      - 8011:8011
    volumes:
      - ./pos:/app
  membership_web:
    image: node:18-slim
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        yarn install
        yarn start
    environment:
      - PORT=8002
      - API_HOST=host.docker.internal:8012
    ports:
      - 8002:8002
    volumes:
      - ./membership:/app
      - membership-node-modules:/app/node_modules
      - membership-parcel-cache:/app/.parcel-cache
  membership_api:
    image: rubylang/ruby:3.2-dev-jammy
    command:
      - /bin/bash
      - -c
      - |
        cd /app
        bundle install
        ./bin/rails s -p 8012 -b 0.0.0.0
    ports:
      - 8012:8012
    volumes:
      - ./membership:/app

volumes:
  pos-node-modules:
  pos-parcel-cache:
  membership-node-modules:
  membership-parcel-cache:
